### ISSUE TITLE
Make with no error, but how can I compile it into .app format?

### ISSUE THREAD

**Issue by evansan** [bwrightkc/qbt-mac#2]

**Comment by bwrightkc** [comment]
@evansan Sorry, I don't monitor this page at all...I just upload qbt releases for mac when there's not an official one yet. Here's the commands I use to build and generate an app format:

'''
export QT_QMAKE=/usr/local/cellar/qt/5.11.2_1/bin
./configure
make -j4
$QT_QMAKE/macdeployqt src/qbittorrent.app -dmg

'''
Sorry if I typed something wrong - that's from my head and not copied. The last line there uses macdeployqt to .app and dmg that bad boy.
